#!/bin/zsh

# Help script - displays comprehensive usage information

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
CYAN='\033[0;36m'
MAGENTA='\033[0;35m'
NC='\033[0m'

clear

echo ""
echo "${BLUE}╔═══════════════════════════════════════════════════════════════╗${NC}"
echo "${BLUE}║                                                               ║${NC}"
echo "${BLUE}║${NC}        ${MAGENTA}🐕 WoofMeetup Authentication Scripts Help 🐕${NC}        ${BLUE}║${NC}"
echo "${BLUE}║                                                               ║${NC}"
echo "${BLUE}╚═══════════════════════════════════════════════════════════════╝${NC}"
echo ""

echo "${CYAN}AVAILABLE SCRIPTS${NC}"
echo "${BLUE}═══════════════════════════════════════════════════════════════${NC}"
echo ""
echo "${GREEN}setup-users.sh${NC}"
echo "  Interactive setup to store credentials for 3 users in Keychain"
echo "  ${YELLOW}Usage:${NC} ./shscripts/auth/setup-users.sh"
echo ""
echo "${GREEN}signup.sh [1|2|3] [server-url]${NC}"
echo "  Sign up user and complete onboarding automatically"
echo "  ${YELLOW}Usage:${NC} ./shscripts/auth/signup.sh 1"
echo "  ${CYAN}→ Creates account, completes profile, opens browser${NC}"
echo ""
echo "${GREEN}login.sh [server-url]${NC}"
echo "  Interactive login - prompts you to select which user"
echo "  ${YELLOW}Usage:${NC} ./shscripts/auth/login.sh"
echo "  ${CYAN}→ Shows user menu, logs in, opens browser${NC}"
echo ""
echo "${GREEN}login-all.sh [server-url]${NC}"
echo "  Login all 3 users at once"
echo "  ${YELLOW}Usage:${NC} ./shscripts/auth/login-all.sh"
echo ""
echo "${GREEN}check-auth.sh [1|2|3] [server-url]${NC}"
echo "  Check if a user's session is still valid"
echo "  ${YELLOW}Usage:${NC} ./shscripts/auth/check-auth.sh 1"
echo ""
echo "${GREEN}help.sh${NC}"
echo "  Display this help message"
echo "  ${YELLOW}Usage:${NC} ./shscripts/auth/help.sh"
echo ""

echo "${BLUE}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
echo ""

echo "${CYAN}PASSWORD REQUIREMENTS${NC}"
echo "${BLUE}═══════════════════════════════════════════════════════════════${NC}"
echo ""
echo "  • Minimum 10 characters"
echo "  • At least 1 uppercase letter"
echo "  • At least 1 lowercase letter"
echo "  • At least 1 number"
echo "  • At least 1 symbol"
echo ""
echo "${CYAN}Valid examples:${NC} AlicePass123! | BobSecure456# | CharlieStrong789$"
echo ""

echo "${BLUE}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
echo ""

echo "${MAGENTA}🚀 QUICK START${NC}"
echo ""
echo "${CYAN}1. Setup credentials:${NC}"
echo "   ${YELLOW}./shscripts/auth/setup-users.sh${NC}"
echo "   ${CYAN}→ Enter email, username, password for 3 users${NC}"
echo ""
echo "${CYAN}2. Start server:${NC}"
echo "   ${YELLOW}npm run server${NC}"
echo ""
echo "${CYAN}3. Sign up users (with auto-onboarding):${NC}"
echo "   ${YELLOW}./shscripts/auth/signup.sh 1${NC}"
echo "   ${YELLOW}./shscripts/auth/signup.sh 2${NC}"
echo "   ${YELLOW}./shscripts/auth/signup.sh 3${NC}"
echo "   ${CYAN}→ Each opens browser to home page${NC}"
echo ""
echo "${CYAN}4. Login anytime (interactive):${NC}"
echo "   ${YELLOW}./shscripts/auth/login.sh${NC}"
echo "   ${CYAN}→ Select user from menu, opens browser to login page${NC}"
echo ""
echo "${CYAN}5. Verify authentication:${NC}"
echo "   ${YELLOW}./shscripts/auth/check-auth.sh 1${NC}"
echo ""

echo "${BLUE}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
echo ""

echo "${MAGENTA}📋 USAGE EXAMPLES${NC}"
echo ""
echo "${YELLOW}Example 1: Complete Workflow${NC}"
echo "  ${GREEN}# Setup${NC}"
echo "  ./shscripts/auth/setup-users.sh"
echo ""
echo "  ${GREEN}# Sign up all users${NC}"
echo "  ./shscripts/auth/signup.sh 1  ${CYAN}# Browser opens to home page${NC}"
echo "  ./shscripts/auth/signup.sh 2  ${CYAN}# Browser opens to home page${NC}"
echo "  ./shscripts/auth/signup.sh 3  ${CYAN}# Browser opens to home page${NC}"
echo ""
echo "  ${GREEN}# Later, login interactively${NC}"
echo "  ./shscripts/auth/login.sh     ${CYAN}# Select user, browser opens to login${NC}"
echo ""
echo "${YELLOW}Example 2: Custom Server${NC}"
echo "  ./shscripts/auth/signup.sh 1 http://localhost:3000"
echo "  ./shscripts/auth/login.sh http://localhost:3000"
echo ""
echo "${YELLOW}Example 3: Batch Login${NC}"
echo "  ./shscripts/auth/login-all.sh  ${CYAN}# Login all 3 users${NC}"
echo ""

echo "${BLUE}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
echo ""

echo "${MAGENTA}🔧 ONBOARDING DETAILS${NC}"
echo ""
echo "When you run ${YELLOW}signup.sh${NC}, it automatically:"
echo "  ${GREEN}✓${NC} Creates the account"
echo "  ${GREEN}✓${NC} Sets dog's name (TestDog1, TestDog2, TestDog3)"
echo "  ${GREEN}✓${NC} Sets age (3 years)"
echo "  ${GREEN}✓${NC} Sets about text (\"Test user 1\", etc.)"
echo "  ${GREEN}✓${NC} Configures meetup preferences"
echo "  ${GREEN}✓${NC} Sets search radius (10 miles)"
echo "  ${GREEN}✓${NC} Opens browser to home page with login instructions"
echo ""
echo "You get a ${CYAN}fully configured test user${NC} ready to use!"
echo ""

echo "${BLUE}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
echo ""

echo "${MAGENTA}🍪 SESSION MANAGEMENT${NC}"
echo ""
echo "Session cookies are saved to:"
echo "  ${YELLOW}/tmp/woofmeetup_cookies_user1.txt${NC}"
echo "  ${YELLOW}/tmp/woofmeetup_cookies_user2.txt${NC}"
echo "  ${YELLOW}/tmp/woofmeetup_cookies_user3.txt${NC}"
echo ""
echo "Use with curl:"
echo "  ${GREEN}curl -b \"/tmp/woofmeetup_cookies_user1.txt\" \\${NC}"
echo "    ${GREEN}http://localhost:8000/api/auth/check-auth${NC}"
echo ""

echo "${BLUE}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
echo ""

echo "${MAGENTA}🔐 KEYCHAIN MANAGEMENT${NC}"
echo ""
echo "${CYAN}View stored credentials:${NC}"
echo "  security find-generic-password -s woofmeetup-user1"
echo ""
echo "${CYAN}Update credentials:${NC}"
echo "  security delete-generic-password -s woofmeetup-user1"
echo "  ./shscripts/auth/setup-users.sh"
echo ""
echo "${CYAN}Delete credentials:${NC}"
echo "  security delete-generic-password -s woofmeetup-user1"
echo ""

echo "${BLUE}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
echo ""

echo "${MAGENTA}📚 DOCUMENTATION${NC}"
echo "  ${GREEN}Quick Start:${NC}      ./shscripts/auth/QUICKSTART.md"
echo "  ${GREEN}Full Guide:${NC}       ./shscripts/auth/README.md"
echo "  ${GREEN}All Scripts:${NC}      ./shscripts/README.md"
echo "  ${GREEN}Summary:${NC}          ./AUTH_SCRIPTS_SUMMARY.md"
echo ""

echo "${BLUE}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
echo ""

echo "${MAGENTA}❓ TROUBLESHOOTING${NC}"
echo ""
echo "${YELLOW}\"No users found in Keychain\"${NC}"
echo "  → Run ${GREEN}./shscripts/auth/setup-users.sh${NC} first"
echo ""
echo "${YELLOW}\"User already exists\"${NC}"
echo "  → User is already signed up, use ${GREEN}./shscripts/auth/login.sh${NC}"
echo ""
echo "${YELLOW}\"Invalid credentials\"${NC}"
echo "  → Check password meets requirements (10+ chars, mixed case, number, symbol)"
echo ""
echo "${YELLOW}\"Browser doesn't open\"${NC}"
echo "  → macOS only. On Linux, edit scripts to use ${GREEN}xdg-open${NC} instead of ${GREEN}open${NC}"
echo ""

echo "${BLUE}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
echo ""

echo "${CYAN}💡 Tips:${NC}"
echo "  • Credentials are stored securely in macOS Keychain"
echo "  • Session cookies persist until system reboot"
echo "  • You can customize onboarding data in signup.sh"
echo "  • All scripts support custom server URLs"
echo "  • Interactive login shows all available users"
echo ""

echo "${GREEN}Happy testing! 🐕 🎉${NC}"
echo ""